# [build]
# Using lld as the linker greatly improve compilation times
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-args=-fuse-ld=lld", "-C", "target-cpu=native"]
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-fuse-ld=lld", "-C", "target-cpu=native"]
[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-fuse-ld=lld", "-C", "target-cpu=native"]
[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "link-args=-fuse-ld=lld", "-C", "target-cpu=native"]


# to run WASM tests
[target.wasm32-wasip1]
runner = "wasmtime"
