name: benchmarks

on:
  push:
    branches:
      - "*"

jobs:
  benchmarks:
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    container: rust:latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64

    steps:
      - uses: actions/checkout@v4
      - run: |
          apt update && apt upgrade -y && apt install -y lld
          cat /proc/cpuinfo
          cargo --version
      - run: make bench
