name: release

on:
  push:
    branches:
      - release

jobs:

  cargo-publish:
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt install -y lld
          rustup update stable

      - name: cargo publish chacha12-blake3
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish -p chacha12-blake3
