name: test

on:
  push:
    branches:
      - main

jobs:
  tests_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update packages
        run: |
          sudo apt install -y lld
          rustup update stable

      - name: Run tests
        run: |
          make test
          RUSTFLAGS="-C target-feature=-avx2" make test

  tests_arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Update packages
        run: |
          sudo apt install -y lld
          rustup update stable

      - name: Run tests
        run: |
          make test
          RUSTFLAGS="-C target-feature=-neon" make test
